// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package maintenance

import (
	"GeoDigitalMap-messageRelayService/api/maintenance"
)

type ControllerV1 struct{}

func NewV1() maintenance.IMaintenanceV1 {
	return &ControllerV1{}
}
