// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventLinkDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventLinkDao = *internal.TMsgEventLinkDao

// tMsgEventLinkDao is the data access object for the table t_msg_event_link.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventLinkDao struct {
	internalTMsgEventLinkDao
}

var (
	// TMsgEventLink is a globally accessible object for table t_msg_event_link operations.
	TMsgEventLink = tMsgEventLinkDao{
		internal.NewTMsgEventLinkDao(),
	}
)

// Add your custom methods and functionality below.
