// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventColorDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventColorDao = *internal.TMsgEventColorDao

// tMsgEventColorDao is the data access object for the table t_msg_event_color.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventColorDao struct {
	internalTMsgEventColorDao
}

var (
	// TMsgEventColor is a globally accessible object for table t_msg_event_color operations.
	TMsgEventColor = tMsgEventColorDao{
		internal.NewTMsgEventColorDao(),
	}
)

// Add your custom methods and functionality below.
