// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventUidDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventUidDao = *internal.TMsgEventUidDao

// tMsgEventUidDao is the data access object for the table t_msg_event_uid.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventUidDao struct {
	internalTMsgEventUidDao
}

var (
	// TMsgEventUid is a globally accessible object for table t_msg_event_uid operations.
	TMsgEventUid = tMsgEventUidDao{
		internal.NewTMsgEventUidDao(),
	}
)

// Add your custom methods and functionality below.
