// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventRemarksDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventRemarksDao = *internal.TMsgEventRemarksDao

// tMsgEventRemarksDao is the data access object for the table t_msg_event_remarks.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventRemarksDao struct {
	internalTMsgEventRemarksDao
}

var (
	// TMsgEventRemarks is a globally accessible object for table t_msg_event_remarks operations.
	TMsgEventRemarks = tMsgEventRemarksDao{
		internal.NewTMsgEventRemarksDao(),
	}
)

// Add your custom methods and functionality below.
