// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventServerDestinationDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventServerDestinationDao = *internal.TMsgEventServerDestinationDao

// tMsgEventServerDestinationDao is the data access object for the table t_msg_event_server_destination.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventServerDestinationDao struct {
	internalTMsgEventServerDestinationDao
}

var (
	// TMsgEventServerDestination is a globally accessible object for table t_msg_event_server_destination operations.
	TMsgEventServerDestination = tMsgEventServerDestinationDao{
		internal.NewTMsgEventServerDestinationDao(),
	}
)

// Add your custom methods and functionality below.
