// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventChatDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventChatDao = *internal.TMsgEventChatDao

// tMsgEventChatDao is the data access object for the table t_msg_event_chat.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventChatDao struct {
	internalTMsgEventChatDao
}

var (
	// TMsgEventChat is a globally accessible object for table t_msg_event_chat operations.
	TMsgEventChat = tMsgEventChatDao{
		internal.NewTMsgEventChatDao(),
	}
)

// Add your custom methods and functionality below.
