// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventSensorDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventSensorDao = *internal.TMsgEventSensorDao

// tMsgEventSensorDao is the data access object for the table t_msg_event_sensor.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventSensorDao struct {
	internalTMsgEventSensorDao
}

var (
	// TMsgEventSensor is a globally accessible object for table t_msg_event_sensor operations.
	TMsgEventSensor = tMsgEventSensorDao{
		internal.NewTMsgEventSensorDao(),
	}
)

// Add your custom methods and functionality below.
