// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventSummaryDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventSummaryDao = *internal.TMsgEventSummaryDao

// tMsgEventSummaryDao is the data access object for the table t_msg_event_summary.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventSummaryDao struct {
	internalTMsgEventSummaryDao
}

var (
	// TMsgEventSummary is a globally accessible object for table t_msg_event_summary operations.
	TMsgEventSummary = tMsgEventSummaryDao{
		internal.NewTMsgEventSummaryDao(),
	}
)

// Add your custom methods and functionality below.
