// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventHowDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventHowDao = *internal.TMsgEventHowDao

// tMsgEventHowDao is the data access object for the table t_msg_event_how.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventHowDao struct {
	internalTMsgEventHowDao
}

var (
	// TMsgEventHow is a globally accessible object for table t_msg_event_how operations.
	TMsgEventHow = tMsgEventHowDao{
		internal.NewTMsgEventHowDao(),
	}
)

// Add your custom methods and functionality below.
