// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventContactDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventContactDao = *internal.TMsgEventContactDao

// tMsgEventContactDao is the data access object for the table t_msg_event_contact.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventContactDao struct {
	internalTMsgEventContactDao
}

var (
	// TMsgEventContact is a globally accessible object for table t_msg_event_contact operations.
	TMsgEventContact = tMsgEventContactDao{
		internal.NewTMsgEventContactDao(),
	}
)

// Add your custom methods and functionality below.
