// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventTrackDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventTrackDao = *internal.TMsgEventTrackDao

// tMsgEventTrackDao is the data access object for the table t_msg_event_track.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventTrackDao struct {
	internalTMsgEventTrackDao
}

var (
	// TMsgEventTrack is a globally accessible object for table t_msg_event_track operations.
	TMsgEventTrack = tMsgEventTrackDao{
		internal.NewTMsgEventTrackDao(),
	}
)

// Add your custom methods and functionality below.
