// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventPointDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventPointDao = *internal.TMsgEventPointDao

// tMsgEventPointDao is the data access object for the table t_msg_event_point.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventPointDao struct {
	internalTMsgEventPointDao
}

var (
	// TMsgEventPoint is a globally accessible object for table t_msg_event_point operations.
	TMsgEventPoint = tMsgEventPointDao{
		internal.NewTMsgEventPointDao(),
	}
)

// Add your custom methods and functionality below.
