// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventVideoDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventVideoDao = *internal.TMsgEventVideoDao

// tMsgEventVideoDao is the data access object for the table t_msg_event_video.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventVideoDao struct {
	internalTMsgEventVideoDao
}

var (
	// TMsgEventVideo is a globally accessible object for table t_msg_event_video operations.
	TMsgEventVideo = tMsgEventVideoDao{
		internal.NewTMsgEventVideoDao(),
	}
)

// Add your custom methods and functionality below.
