// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventUsericonDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventUsericonDao = *internal.TMsgEventUsericonDao

// tMsgEventUsericonDao is the data access object for the table t_msg_event_usericon.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventUsericonDao struct {
	internalTMsgEventUsericonDao
}

var (
	// TMsgEventUsericon is a globally accessible object for table t_msg_event_usericon operations.
	TMsgEventUsericon = tMsgEventUsericonDao{
		internal.NewTMsgEventUsericonDao(),
	}
)

// Add your custom methods and functionality below.
