// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventPrecisionLocationDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventPrecisionLocationDao = *internal.TMsgEventPrecisionLocationDao

// tMsgEventPrecisionLocationDao is the data access object for the table t_msg_event_precision_location.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventPrecisionLocationDao struct {
	internalTMsgEventPrecisionLocationDao
}

var (
	// TMsgEventPrecisionLocation is a globally accessible object for table t_msg_event_precision_location operations.
	TMsgEventPrecisionLocation = tMsgEventPrecisionLocationDao{
		internal.NewTMsgEventPrecisionLocationDao(),
	}
)

// Add your custom methods and functionality below.
