// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventMcvDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventMcvDao = *internal.TMsgEventMcvDao

// tMsgEventMcvDao is the data access object for the table t_msg_event_mcv.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventMcvDao struct {
	internalTMsgEventMcvDao
}

var (
	// TMsgEventMcv is a globally accessible object for table t_msg_event_mcv operations.
	TMsgEventMcv = tMsgEventMcvDao{
		internal.NewTMsgEventMcvDao(),
	}
)

// Add your custom methods and functionality below.
