// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"GeoDigitalMap-messageRelayService/internal/dao/internal"
)

// internalTMsgEventTypeDao is an internal type for wrapping the internal DAO implementation.
type internalTMsgEventTypeDao = *internal.TMsgEventTypeDao

// tMsgEventTypeDao is the data access object for the table t_msg_event_type.
// You can define custom methods on it to extend its functionality as needed.
type tMsgEventTypeDao struct {
	internalTMsgEventTypeDao
}

var (
	// TMsgEventType is a globally accessible object for table t_msg_event_type operations.
	TMsgEventType = tMsgEventTypeDao{
		internal.NewTMsgEventTypeDao(),
	}
)

// Add your custom methods and functionality below.
